sudo: required
cache: 
  directories: 
    - "$HOME/.m2"

services:
  - docker

language: java
jdk:
  - oraclejdk

before_script:
  - echo "MAVEN_OPTS='-Xmx1024m -XX:MaxPermSize=256m'" > ~/.mavenrc
script:
  - mvn clean install

install: travis_wait 30 mvn install
